# Generated by Django 3.2.3 on 2021-09-25 15:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Название должно быть длиннее чем 1 символ')])),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Место должно быть длиннее чем 1 символ')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Имя должно быть длиннее чем 1 символ')])),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+99999999999'. ", regex='^\\+?1?\\d{11}$')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Название должно быть длиннее чем 1 символ')])),
            ],
        ),
        migrations.CreateModel(
            name='Team_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CP', 'Капитан'), ('MP', 'Основной игрок'), ('EP', 'Неактивный')], default='MP', max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorm.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorm.team')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainstorm.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainstorm.player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainstorm.team')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('correct', models.BooleanField(null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorm.contest')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorm.game'),
        ),
        migrations.AddField(
            model_name='contest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorm.team'),
        ),
    ]
