# Generated by Django 3.2.3 on 2021-10-04 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Зарегистрировавшаяся команда', 'verbose_name_plural': 'Зарегистрировавшиеся команды'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос игры', 'verbose_name_plural': 'Вопросы игры'},
        ),
        migrations.AlterModelOptions(
            name='roster',
            options={'verbose_name': 'Состав команды', 'verbose_name_plural': 'Составы команд'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='team_player',
            options={'verbose_name': 'Команда игрока', 'verbose_name_plural': 'Команды игроков'},
        ),
        migrations.AlterField(
            model_name='game',
            name='date_time',
            field=models.DateTimeField(verbose_name='дата и время'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Место должно быть длиннее чем 1 символ')], verbose_name='Место проведение'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Название должно быть длиннее чем 1 символ')], verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Имя должно быть длиннее чем 1 символ')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+99999999999'. ", regex='^\\+?1?\\d{11}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.BooleanField(null=True, verbose_name='Вопрос взят'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер вопроса'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Название должно быть длиннее чем 1 символ')], verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='team_player',
            name='status',
            field=models.CharField(choices=[('CP', 'Капитан'), ('MP', 'Основной игрок'), ('EP', 'Неактивный')], default='MP', max_length=2, verbose_name='Статус игрока'),
        ),
    ]
