# Generated by Django 3.2.3 on 2021-10-17 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0003_auto_20211016_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id_site',
        ),
        migrations.AddField(
            model_name='team',
            name='id_site',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Id для выгрузки на сайт ЧГК'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Место должно быть длиннее чем 1 символ')], verbose_name='Место проведения'),
        ),
    ]
